# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0ObQubO27ceBsdJUdIqnxJhYi7s3P8y
"""

s = "  Python Programming  "
print("Original String:", s)
# Case conversion
print("Uppercase:", s.upper())
print("Lowercase:", s.lower())
print("Title Case:", s.title())
print("Capitalize:", s.capitalize())
print("Swapcase:", s.swapcase())
# Removing spaces
print("Strip:", s.strip())
print("Left Strip:", s.lstrip())
print("Right Strip:", s.rstrip())
# Length of string
print("Length:", len(s))
# Searching and counting
print("Count of 'o':", s.count('o'))
print("Find 'Program':", s.find("Program"))
# Replace
print("Replace Python with Java:", s.replace("Python", "Java"))
# Splitting
words = s.split()
print("Split into words:", words)
# Joining
joined = "-".join(words)
print("Joined string:", joined)
# Checking functions
s2 = "Python123"
print("Is Alpha:", s2.isalpha())
print("Is Alphanumeric:", s2.isalnum())
print("Is Digit:", s2.isdigit())
# Startswith and Endswith
print("Starts with 'Python':", s.strip().startswith("Python"))
print("Ends with 'ing':", s.strip().endswith("ing"))
# String formatting
name = "Anu"
age = 21

